name: publish

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/setup-node@v2

    - name: Install parcel
      run: |
        sudo npm install -g parcel

    - name: Build site
      run: |
        parcel build index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: live # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.

    - uses: actions/setup-python@v2
    - name: BackBlaze deploy
      run: |
        python -m pip install --upgrade pip
        pip install --quiet --no-cache-dir b2==2.1.0
        b2 authorize-account ${B2_APPKEY_ID} ${B2_APPKEY}
        b2 sync --delete --replaceNewer ${SOURCE_DIR} b2://hgeometry
        b2 clear-account
      env:
        SOURCE_DIR: './assets'
        B2_BUCKET: ${{ secrets.B2_BUCKET }}
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}
