name: publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install parcel
      run: |
        sudo npm install -g parcel

    - name: Build site
      run: |
        parcel build index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: live # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
